### ISSUE TITLE
Support AirLeaf

### ISSUE THREAD

**Issue by alecad** [danielrivard/homeassistant-innova#65] opened 2022-10-18 06:11 UTC
It will be great to implement support for Innova AirLeaf devices.
Now, with current version there's error in temp values, and also the operation mode doesn't match.
Write back if need more details
tnx!

![image](https://user-images.githubusercontent.com/101917365/196349000-d31ba26f-769b-4640-8d9d-dba3384b0b1e.png)

this is the result of status api call:
```json
{
  "success": true,
  "sw": {
    "V": "1.0.3"
  },
  "UID": "f4:cf:a2:5f:29:ef",
  "deviceType": "002",
  "time": {
    "d": 18,
    "m": 10,
    "y": 2022,
    "h": 6,
    "i": 14
  },
  "net": {
    "ip": "192.168.1.63",
    "sub": "255.255.255.0",
    "gw": "192.168.1.1",
    "dhcp": "1"
  },
  "setup": {
    "serial": "",
    "name": ""
  },
  "RESULT": {
    "sp": 200,
    "wm": 3,
    "fn": 1,
    "kl": 0,
    "lastworkingModeSet": 0,
    "ps": 0,
    "cm": 0,
    "a": [],
    "ta": 210,
    "tw": 219,
    "ns": 0,
    "cloudStatus": 4,
    "connectionStatus": 2,
    "cloudConfig": 1,
    "timerStatus": 0,
    "inputFlags": 0,
    "ncc": 0,
    "lcc": 0,
    "pwd": "",
    "heap": 11496,
    "ccv": 0,
    "cci": 0,
    "daynumber": 0,
    "uptime": 90675,
    "fclFw": 24,
    "uscm": 0,
    "lastRefresh": 2
  }
}
```

**Comment by danielrivard** [comment] 2022-10-19 23:15
The result of the status API seems similar enough that it would hint to the rest of the API being similar as well.

`deviceType: 002` would be helpful to distinguish the 2 models, as the 2.0 has a `deviceType: 001`.

But it is hard to really be sure without the ability to play with it myself.

At first glance, I would think that 
`sp` is same and is set point.
`ta` could be ambient temperature
`tw` could be water temperature
and they all seem to be multiplied by 10, so 219 could be 21.9 C.

For the operation mode, you would need to experiment by changing the mode in the Innova App and finding the associated value in the `wm` field of the status json. This way I could adjust the mapping in the integration.

**Comment by danielrivard** [comment] 2022-10-19 23:21
Also, I don't know if you removed the serial value from the `"setup":{"serial":"","name":""}` section, but it is needed to have a serial number for the integration to work well in home assistant, it is what will give it a unique id in all the entities.

**Comment by alecad** [comment] 2022-10-20 06:16
> 
wm 3: mode heating
wm 5:  mode cooling
i can't find others wm values, changing setting from innova app (there's no dehumidification or fanonly)

there s also the fn variable that could have following values:
fn 1: auto
fn 2: night
fn 3: low vent
fn 4: max vent

i haven't removed serial and name values, They 're empty in all devices (may be that the cloud do the match)
In this case the UID value could be used as unique id

**Comment by alecad** [comment] 2022-10-22 05:14
Great!
Thank You!
If u need more infos or tests, just let me know how to help you.

**Comment by VasilisMavr** [comment] 2023-01-14 07:22
Hi I am also very interested to see if this is going to work

I have managed to integrate the airleafs via modbus RTU to HA, but cant do all of them 

The values indicated by alecad for the airleaf are very similar to the modbus values which are given in a manual by innova when setting modbus

Hope these might be of some help

Here are the values for modbus which i am sure are the same or very similar for IP setup

Modbus Register 201 which I think maps to "fn" has these working values
0 : Auto fan
1 : Low Fan
2 :  Fan Night mode
3 : High Fan
128 : Switches Fan Coil Off - Trigerring in Modbus 0,1,2 or 3 as teh fan mode also switches on the fan coil

Modbus Register 233 which I think maps to "wm" has these working values
0 : Auto - this cant be selected on the fan coil panel but can be triggered by modbus and works well
3 : Heating Mode
5 : Cooling Mode

On Modbus the registers for ambient temperature, water temperature and setpoint all need multiplying by ten to sent the value to the fan coil or divide by ten to get the right value from the fan coil

Hope this help

**Comment by VasilisMavr** [comment] 2023-01-14 07:23
PS I am also very happy to support testing

Happy New Year

**Comment by danielrivard** [comment] 2023-01-16 20:36
Sorry, I haven't been able to put much time into this in the last few months, I'll try to make some progress soon.

And thanks for the test offering, I'll definitely need some help as I don't own an AirLeaf myself.

**Comment by mynkow** [comment] 2023-01-21 19:10
Hello, I am about to purchase a lot of AirLeaf units and I plan to add them all to my home automation system.

I have contacted the Innova support and asked them what are the options to control devices such as `Innova AirLeav SL600` and they said that the only option is through a `mod bus` and the corresponding [docs](https://www.innovaenergie.com/site/assets/files/2792/n273025c_kit_bridge_modbus_rtu_rev_01_en.pdf)

You guys are dong simple http requests to control the units. I really like this and I could assist with the development. Could you please share what is your equipment in order to setup my environment and purchase the units so that I could control them via HTTP (way easier than `modbus`)?

Also, what is the component number and the model of your control module coming from innova?

**Comment by danielrivard** [comment] 2023-01-27 17:31
I was able to make good progress this week. I think I could have a working version next week.

If you are familiar with Python, you can look at the [innova-controls library branch](https://github.com/danielrivard/innova-controls/tree/6-add-support-for-innova-airleaf) I created for this.

You would need to create a virtualenv, install requirements.txt and then you could play with [src/test_main.py](https://github.com/danielrivard/innova-controls/blob/6-add-support-for-innova-airleaf/src/test_main.py) to send some commands to the AirLeaf.

The changes are not yet supported by the HA integration, it just works in the underlying library.

**Comment by VasilisMavr** [comment] 2023-01-28 23:09
Thank you for progressing this

Not that familiar with Python at 

Will have a look but hesitant to try many things in case I break something 

Vas

**Comment by danielrivard** [comment] 2023-01-29 00:15
I did not intend to close the issue yet,but merging the code did it automatically it seems.

Anyway you may not need play with Python. The merged code should work with Airleaf.

I will create a beta release for HACS later, but in the meantime you can do a manual install of the main branch. The readme has the instructions.

**Comment by danielrivard** [comment] 2023-01-29 01:14
See Discussion on the beta release to see how to install beta versions through HACS, and add any comment on issues you encounter. I'll try to fix them as best I can.

Two possible limitations of the integration:

1. In Home Assistant, sleep mode is part of their Presets, not available as a Fan mode, so if you need this feature, use the preset. The Fan will display Auto in this case.
2. From what I found in the AirLeaf/Fancoil http API, it is not clear if this will work. In Home Assistant, this mode is Heat/Cool.

**Comment by VasilisMavr** [comment] 2023-01-30 19:27
Thank you Daniel

I have installed it manually and run some tests today and here are the results

Mostly the integration can for sure read the Fancoil values and states and status

1. When the temperature is changed in HA it will not change in the Fancoil - what happens is that a few seconds later the value in HA reverts to the Fancoil one
2. The Off button when pressed it switches the FC off but it does not switch ON that easily via HA ( had a similar issue with modbus, to switch it on you need to select a FAN state like AUTO/SLEEP/LOW/HIGH to switch it back on)

On the bright side when the FC is in the on position
3. Selecting Heating or Colling works - auto does not work
4. The fan speed of AUTO/LOW/HIGH can be selected and work
5. The Sleep preset also works

I will give it another test later this week as I am now travelling till Sunday

Thanks for the effort and the great work so far

Vas

**Comment by danielrivard** [comment] 2023-01-30 23:26
1. I think I found the problem with the temperature change, there is a slight difference in the parameter. I will fix the bug this week.
2. Yeah this is somewhat a limitation of how HA works, it offers a turn off option when the device is on, but to turn it on, you need to choose a mode.
3. I thought so, looking at the Android app for the fancoil, it does not seem to support the Heat/Cool (Auto) mode

Good to know the rest works

**Comment by danielrivard** [comment] 2023-01-31 01:44
@VasilisMavr for problem #2, does the Airleaf automatically turns on if you select a mode while it is turned off? My innova 2.0 does that, so when turned off, I can just start it by selecting a mode.

If the Airleaf does not behave the same way, a potential solution could be to send a `power on` command in the background when receiving a `set mode` command.

**Comment by alecad** [comment] 2023-01-31 07:24
Hi I tried to test and i can confirm @VasilisMavr. The Airleaf dosn't turn on if i select a mode.
I can't find a way to turn it on from home assistant.
Calling the rest api it work posting on /api/v/1/power/on .
posting the api /api/v/1/set/mode/auto returns  404

**Comment by alecad** [comment] 2023-01-31 07:52
I can confirm that in the innova app there's no auto mode, just heat or cold.
And in that app isn't possible to set modes on single FC, but just in the whole home.
"Auto" is an option just to set the fan speed on single FC.

**Comment by danielrivard** [comment] 2023-01-31 23:19
Just published version [1.2.2](https://github.com/danielrivard/homeassistant-innova/releases/tag/v1.2.2) which will power on the device when setting a mode from the HA UI.  It is not a beta, so it should be available through HACS.

Please give it a try when you have a chance.

**Comment by alecad** [comment] 2023-02-01 06:33
thank you for all!
I've tested it but the problem 1 "When the temperature is changed in HA it will not change in the Fancoil" seems still there

**Comment by alecad** [comment] 2023-02-01 10:16
I'm also having troubles, adding more then One device. (Static ip).
When add device1 then device2 only device1 Is recognized.
Delete both.
When add device2 then device1 only device2 Is recognized.
It's my fault?

**Comment by danielrivard** [comment] 2023-02-01 19:03
@alecad for the temperature change, could you try to send a command directly to the unit
`curl -d "temp=200" -X POST http://192.168.XX.XX/api/v/1/set/setpoint`

And see if this returns an error?

For multiple devices issue, this was not super well tested, as I only own one unit myself, so I may need to revisit this logic, I thought it would have one instance per ip address, but that might not be the case. 


@VasilisMavr The library can already report the water value, so I could add it as an HA sensor without too much effort.

**Comment by danielrivard** [comment] 2023-02-02 03:19
@alecad I was able to create a simulator that returns fake response to the same rest calls, and I am able to add 2 different units to Home Assistant and they are behaving independently.

I think the problem is that you don't have a serial number set on your device as shown in the status json you had put at the beginning of this ticket. 

The serial number is used as the unique identifier when registering a device to Home Assistant, so that is probably why you can only add one at a time.

I think I saw somewhere in the Innova documentation how to set the serial number but can't remember where.

**Comment by alecad** [comment] 2023-02-02 07:16
Hi
i'm able to set serial with curl -d "serial=123456789&name=test" -X POST http://192.168.xx.xx/api/v/1/setup
... not so user friendly but it works an now i can add devices in HA.

But i can't set the temp:
$ curl -d "temp=230" -X POST http://192.168.xx.xx/api/v/1/set/setpoint
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     8    0     0    0     8      0      0 --:--:--  0:00:19 --:--:--     0
curl: (56) Recv failure: Connection was reset


GET / POSTS to others endpoint works on same ip. 

it seems a wrong call to the api, i'm still tring to get it works.....

**Comment by danielrivard** [comment] 2023-02-02 13:10
I did find a bug in the code where the temperature is multiplied by 100 instead of 10. I will fix this and publish an update later today or tomorrow.

But if the curl command does not work, we may not have the right API endpoint or payload.

**Comment by danielrivard** [comment] 2023-02-03 17:16
@alecad Hi, could you try the setpoint endpoint with a JSON payload to see if that works?

`curl -d '{"temp":230}' -H 'Content-Type: application/json' -X POST http://192.168.xx.xx/api/v/1/set/setpoint`

**Comment by alecad** [comment] 2023-02-03 17:24
i'm using InnovApp to control my fancoils and it's not possibile to set serial.
Yes with json payload it works! Great! Thank You!

**Comment by danielrivard** [comment] 2023-02-03 17:32
Good! I will update the library to send json payload for AirLeaf. 

Thanks for the testing effort, I should be able to release a new version very soon.

**Comment by alecad** [comment] 2023-02-04 15:53
I've tested it.
The only thing is that when serial is empty, there's no way to distinguish between different fancoils.
Setting serial with rest api call, cause troubles in innovApp (loosing control of FC).
I've tested a solution on HA, using UID when serial is empty, it works.
I've created a pull request with that patch ;)

**Comment by danielrivard** [comment] 2023-02-04 18:29
Thanks for the pull requests, I've made some slight adjustments to make the code a little cleaner (at least in my subjective opinion, everyone has different standards).

I'll run some tests, then merge to main branch, and push a release.

**Comment by danielrivard** [comment] 2023-02-08 14:06
Let me know when you have used the integration with AirLeaf for a week or so and if it stable.  We will then close this ticket, and if any bugs happen after that we can just create new tickets to fix them.

**Closed** 2023-02-11 19:36 UTC
