### ISSUE TITLE
Can't seem to have more than one unit/entity at a time. 

### ISSUE THREAD

**Issue by GueteBueb** [danielrivard/homeassistant-innova#12] opened 2022-05-22 19:36 UTC
I've added the integration according to your instructions and  I have been able to add both of my devices but not at the same time.
I did not receive any errors in my logs so far but I also haven't been able to find two separate entities for the devices yet.

Entry in configuration.yaml:

```
climate:
  - platform: innova
    host: 192.168.1.17
    scan_interval: 900
  - platform: innova
    host: 192.168.1.18
    scan_interval: 900
```

**Comment by danielrivard** [comment] 2022-05-22 20:39
Unfortunately I only own a single device, so I cannot reproduce this scenario.
@cybert79 had reported an [issue](https://github.com/danielrivard/homeassistant-innova/issues/2) and seemed to be able to control their 3 units with this configuration.

If you go to the entities list and filter for innova, what do you see? Maybe you would need to change the entities IDs manually?

http://homeassistant:8123/config/entities

![image](https://user-images.githubusercontent.com/2893453/169714769-7691cf33-4d2b-4679-9a44-2948d3d0973b.png)

**Comment by cybert79** [comment] 2022-05-23 07:52
climate:
  - platform: innova
    host: 192.168.1.134
    scan_interval: 1200
  - platform: innova
    host: 192.168.1.126
    scan_interval: 1200
  - platform: innova
    host: 192.168.1.129
    scan_interval: 1200

Did you added them via the innova app to your wifi? Do note that you have the give them all a different serial nr, I used for exaple IN1234567 for the first unit, IN1234568 for the second one and IN1234659 for the third one.
<img width="905" alt="Screenshot 2022-05-23 095206" src="https://user-images.githubusercontent.com/16208462/169770323-6ada6b44-bc27-4e6b-8f4b-1a3b0848cc7f.png">
<img width="917" alt="Screenshot 2022-05-23 095307" src="https://user-images.githubusercontent.com/16208462/169770497-4dca8a3a-b202-40fb-bbda-cfe27ce5562a.png">

**Comment by Robby-Swartenbroekx** [comment] 2022-05-23 09:01
you can change these serial numbers yourself??? isn't this a number that is fixed in the device itself?
The reason I'm asking this, is that I see 2 of my 4 devices share a serial number and I though on faulty hardware, but if this is something we can change/reset that would be great.

**Comment by cybert79** [comment] 2022-05-23 09:02
Well, they don't check the serial nr,... It just has to be a different one and start with in12345

**Comment by cybert79** [comment] 2022-05-23 09:08
> @cybert79: you can change these serial numbers yourself??? isn't this a number that is fixed in the device itself? The reason I'm asking this, is that I see 2 of my 4 devices share a serial number and I though on faulty hardware, but if this is something we can change/reset that would be great.

You will have to reset your wifi modules on the innova's and re-add them with the app
<img width="839" alt="Screenshot 2022-05-23 110943" src="https://user-images.githubusercontent.com/16208462/169785165-1c2adfbe-53c0-4dbb-8bd9-8f6c295dac29.png">

**Comment by Robby-Swartenbroekx** [comment] 2022-05-23 18:45
Solved it completely. Thanks @cybert79, and also thanks @danielrivard to make this integration. your work is making multiples people integrations a little bit more complete.

Now I have found all 4 devices in my network flawlessly. I used the serialnumber that was printed on the devices itself (below the grill on the left side). The printed s/n was unique. The one in my home office space had the incorrect one, don't know how that ever happened, but had issues in the past with the whitelabeled apps (My airco's are enrOne, but you can add them to supported devices, it's just a whitelabel for Innova).

**Comment by danielrivard** [comment] 2022-05-23 21:38
I have just released a new version with support for config flow (configuration through ui rather than yaml). I think it may help with setting up multiple devices or at least it might be easier to see when it does not work.

**Comment by danielrivard** [comment] 2022-05-27 20:09
@GueteBueb Did you manage to fix your problem? Can this issue be closed?

**Comment by bLackCat-79** [comment] 2022-05-28 10:52
From my view, it can be closed

**Closed** 2022-05-28 21:16 UTC
